### ISSUE TITLE
Any docs for this?

### ISSUE THREAD

**Issue by tgbv** [firststef/SPEL#5]
it's interesting 😄

**Comment by firststef** [comment]
This project has been an assignment for a college course about compilers. I wanted to develop it further, but the bison/flex framework is too old, therefore I would have to rebuild the project. I designed SPEL not as a programming language-first, but as a fun way to write programs. One of the original ideas was to make the compiler be like a game, in which the player compiles a program designed to fight some fictional monsters by using various programming language features. In other words, I won't be continuing to implement SPEL in c++, but I have started a separate project to integrate SPEL in a game:
[SPEL Ignite](https://github.com/firststef/Spel-Ignite-Web)
You can check back on this in a few months if you are interested, I might be able to revive the language with a few additions.
